apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: olg81jbi9-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:2a547b21fcaf74148963698863e1fff13b46539a@sha256:9ae6b86bff197014aa29823fdd9c05220a4c2e143d2d603a86ede498b23ca6a5
          name: container-image
